package ru.stqa.pft.phishman;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class EmplTest {
  private WebDriver wd;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeMethod
  public void setUp() {
    wd = new ChromeDriver();
    wd.get("https://demo5.phishman.ru/login");
    wd.findElement(By.id("username")).click();
    wd.findElement(By.id("username")).sendKeys("");
    wd.findElement(By.id("password")).click();
    wd.findElement(By.id("password")).sendKeys("");
    wd.findElement(By.id("_submit")).click();
    wd.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
  }
  @AfterMethod
  public void tearDown() {
    wd.quit();
  }

  @Test
  public void empl() throws InterruptedException {

    wd.findElement(By.cssSelector("li:nth-child(2) svg")).click();
    Thread.sleep(1000);
    wd.findElement(By.xpath("//div[@id='root']/div/main/div/div/div/div[2]/span")).click();
    wd.findElement(By.xpath("//div[@id='root']/div/main/div/div/div/div[2]/span")).click();
    wd.findElement(By.xpath("//button[contains(.,'Добавить отдел')]")).click();
    wd.findElement(By.xpath("//input[@type='text']")).click();
    wd.findElement(By.xpath("//input[@type='text']")).sendKeys("Тестирование");
    wd.findElement(By.xpath("//span[contains(.,'Корневой')]")).click();
    wd.findElement(By.xpath("//button[contains(.,'Добавление отдел')]")).click();
    Thread.sleep(1000);
    wd.findElement(By.xpath("//div[@id='root']/div/main/div/div/div/div[2]/span")).click();
    wd.findElement(By.xpath("//button[contains(.,'Добавить сотрудника')]")).click();
    wd.findElement(By.xpath("//input[@type='text']")).click();
    wd.findElement(By.cssSelector(".addTargetInputWrapper:nth-child(1) > .inputField")).sendKeys("Горелкин");
    wd.findElement(By.xpath("(//input[@type='text'])[3]")).click();
    wd.findElement(By.cssSelector(".addTargetInputWrapper:nth-child(3) > .inputField")).sendKeys("Алексей");
    wd.findElement(By.xpath("//div[@id='root']/div/main/div[4]/div/div[2]/div/div[6]/input")).click();
    wd.findElement(By.xpath("//div[@id='root']/div/main/div[4]/div/div[2]/div[2]/div/div[2]/div/div/ul/li[8]/div/label/span[2]")).click();
    wd.findElement(By.cssSelector(".modalWrapper-show .modalFooter:nth-child(2) svg")).click();
    wd.findElement(By.xpath("(//input[@type='text'])[5]")).click();
    wd.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys("Александрович");
    wd.findElement(By.xpath("//div[@id='root']/div/main/div[4]/div/div[2]/div/div[4]")).click();
    wd.findElement(By.xpath("(//input[@type='text'])[2]")).click();
    wd.findElement(By.xpath("(//input[@type='text'])[2]")).sendKeys("gorelkin@alexey.ru");
    wd.findElement(By.xpath("(//input[@type='text'])[4]")).click();
    wd.findElement(By.xpath("(//input[@type='text'])[4]")).sendKeys("Начальник");
    Thread.sleep(1000);
    wd.findElement(By.xpath("//button[contains(.,'Добавить сотрудника')]")).click();
    wd.findElement(By.xpath("//button[contains(.,'Добавить сотрудника')]")).click();
    Thread.sleep(1000);
    wd.findElement(By.xpath("//span[contains(.,'Тестирование')]")).click();
    wd.findElement(By.cssSelector("li:nth-child(3) > .menuItem svg")).click();
    wd.findElement(By.cssSelector("li:nth-child(4) svg")).click();
    wd.findElement(By.cssSelector("li:nth-child(5) svg")).click();
    {
      WebElement element = wd.findElement(By.cssSelector(".menuItem-active"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = wd.findElement(By.tagName("body"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = wd.findElement(By.cssSelector("li:nth-child(6) > .menuItem"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = wd.findElement(By.tagName("body"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element, 0, 0).perform();
    }
    wd.findElement(By.cssSelector("li:nth-child(6) svg")).click();
    wd.findElement(By.cssSelector("li:nth-child(1) svg")).click();
    {
      WebElement element = wd.findElement(By.cssSelector(".menuItem-active path:nth-child(1)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = wd.findElement(By.tagName("body"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
