package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.ContactData;
import ru.stqa.pft.addressbook.TestBase;


public class ContactCreationTests extends TestBase {


  @Test
  public void testContactCreation() {
    app.initContactCreation();
    app.fillContactForm(new ContactData("firstname", "lastname", "89039035555", "mail@mail.ru"));
    app.submitContactCreation();
    app.returnToHomePage();
  }
}
